application:
  name: "useQ AI Assistant"
  version: "1.0.0"
  description: "Intelligent CLI-based AI code assistant"
  
ai_providers:
  primary: "openai"
  fallback_order: ["gemini", "cohere", "claude"]
  
  openai:
    model: "gpt-4-turbo-preview"
    max_tokens: 4000
    temperature: 0.1
    timeout: "30s"
    cost_per_1k_input: 0.01
    cost_per_1k_output: 0.03
    
  gemini:
    model: "gemini-1.5-pro"
    max_tokens: 4000
    temperature: 0.1
    timeout: "30s"
    cost_per_1k_input: 0.0035
    cost_per_1k_output: 0.0105
    
  cohere:
    model: "command-r-plus"
    max_tokens: 4000
    temperature: 0.1
    timeout: "30s"
    cost_per_1k_input: 0.003
    cost_per_1k_output: 0.015
    
  claude:
    model: "claude-3-sonnet-20240229"
    max_tokens: 4000
    temperature: 0.1
    timeout: "30s"
    cost_per_1k_input: 0.003
    cost_per_1k_output: 0.015

indexing:
  supported_languages: ["go"]
  file_extensions:
    go: [".go", ".mod", ".sum"]
  
  exclusion_patterns:
    - "vendor/"
    - "node_modules/"
    - ".git/"
    - "*.test"
    - "*.tmp"
    - ".DS_Store"
    
  embedding:
    model: "text-embedding-3-small"
    dimension: 1536
    batch_size: 100
    chunk_size: 1000
    chunk_overlap: 200
    
vectordb:
  collection_name: "code_embeddings"
  distance_metric: "cosine"
  ef_construct: 200
  m: 16
  
search:
  similarity_threshold: 0.7
  max_results: 10
  enable_reranking: true
  
learning:
  feedback_weight: 1.0
  correction_learning_rate: 0.1
  accuracy_tracking: true
  
  retention:
    feedback_days: 30
    session_days: 7
    metrics_days: 90
    
performance:
  cache:
    enabled: true
    ttl: "1h"
    max_size: "100MB"
    
  rate_limits:
    requests_per_minute: 60
    tokens_per_minute: 60000
    
  optimization:
    lazy_loading: true
    concurrent_requests: 3
    request_pooling: true

# Why this file: 
# This is the central configuration hub defining AI provider settings, costs, models, indexing rules, and performance parameters. 
# It allows easy switching between providers and tuning system behavior.